### ISSUE TITLE
X tags of VR == 'DA' not getting deleted

### ISSUE THREAD

**Issue by smjoshiatglobus** [KitwareMedical/dicom-anonymizer#56]
I found this while looking at pytest failures for "color3d_jpeg_baseline.dcm" file from `pydicom`'s test files. The element [(0020,0244)](https://dicom.innolitics.com/ciods/segmentation/general-series/00400244) was not getting deleted. The tag is listed in `X_TAGS`.

The code for `delete_element` calls `replace_element_date` for `VR=='DA'`, even if the element is supposed to be deleted. I cannot figure out why that is all right. Please help!

**Comment by smjoshiatglobus** [comment]
I found [Section E.3.6](https://dicom.nema.org/medical/dicom/current/output/html/part15.html#sect_E.3.6). Note 2 in that section says that it is all right to set dummy values for dates. Is that the rationale behind this code logic?

**Comment by pchoisel** [comment]
That's a good point, I can also see the issue now that we merged #60 
I will investigate

**Comment by smjoshiatglobus** [comment]
PR #64 does not fix the issue, just puts in temporary exclusion of elements of type `DA`. This has enabled testing of all other tags for test files that were originally failing the test.

**Comment by pchoisel** [comment]
I don't think we want to modify this behavior, by default at least.  
Eventually, we could have a flag that would change the behavior of dicom-anonymizer to delete the DA tags ?

**Comment by smjoshiatglobus** [comment]
Since the dates get anonymized, I guess it is all right even if they are not completely deleted. I am ok if you want to close this issue.
